language: ruby
sudo: false
cache: bundler
before_install: gem install bundler -v 1.11.2
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
