language: ruby
sudo: false
cache: bundler
before_install: gem install bundler -v 1.11.2
rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.0
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
